# Generated by Django 4.2.6 on 2023-11-07 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0002_alter_customuser_managers_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=100)),
                ('lab_room_number', models.CharField(max_length=10)),
                ('number_of_workstations', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('availability_time', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilityDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_days', to='bookingapp.laboratory')),
            ],
        ),
    ]
